[build]


[context.main.environment]
publish = "public"
command = "hugo --gc --minify"
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
HUGO_BASEURL = "/"

[context.community.environment]
  base    = "community/"
  publish = "public/"
  command = "yarn run setup && yarn run build-all"
