[build]
  base = "main"
  command = "hugo --gc --minify"
  publish = "main/public"

[context.production.environment]
    HUGO_VERSION = "0.74.3"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"
    HUGO_BASEURL = "/"


